### ISSUE TITLE
Wasm file 18mb, can we reduce it? This is a significant challenge for the server

### ISSUE THREAD

**Issue by laizeping** [laurentmmeyer/ghostscript-pdf-compress.wasm#2]
I think we just need to compress the code resources of the PDF, which is more lightweight

**Comment by laurentmmeyer** [comment]
Hey @laizeping,

(I'm on a conference, excuse the brief answer)

If you checkout the partial branch, it's 14mb and not 18mb (and stored on a
CDN). To reduce it further, I'll need to dig into Ghostscript.

Let me come back to you.

**Comment by laizeping** [comment]
Thank you, looking forward to your update. This is a PDF compression technology that the web has never had before。
I tried to compile Ghostscript by myself and only keep the compressed PDF part, but my technology does not allow it. I encountered many problems, which made me give up. I'm sorry
