### ISSUE TITLE
This tool is very powerful, I think it can create more tools

### ISSUE THREAD

**Issue by laizeping** [laurentmmeyer/ghostscript-pdf-compress.wasm#3]
such as
PDF TO WORD
PDF TO
I am looking forward to the birth of the PDF TO WORD tool. Can you tell me if it is feasible
Excuse me, thank you for answering my question

I found some issues
Can only be executed once, the second call requires refreshing the page, as it is a context execution, can this be resolved?

**Comment by laurentmmeyer** [comment]
> Can only be executed once, the second call requires refreshing the page, as it is a context execution, can this be resolved?

It is resolved on the commercial branch with a web worker


> PDF TO WORD

Not with ghostscript: https://stackoverflow.com/a/9614636/2545832
