### ISSUE TITLE
Is there a maximum pdf size limit?

### ISSUE THREAD

**Issue by TIT8** [laurentmmeyer/ghostscript-pdf-compress.wasm#4]
Hello, Lorenzo here.

Thank you for your demo and for opensourcing it. I was trying to do the same thing you did, but in vanilla javascript. It's for a website hosting notes from student of the Mylan Politechnic, so embedding the pdf compression on the website would be amazing for us.

With my demo and yours, everything run smootly and good for files of size less than 5Mb. After trying to upload files bigger than 15Mb, the demo alert me of being unresponsive and it never ends the compression.

Is this by design or an hard limitation that I cannot bypass (if my PC is slow, the compression will be slow)? 

Thank you in advance for your time.

**Comment by laurentmmeyer** [comment]
There is a [commercial branch](https://github.com/laurentmmeyer/ghostscript-pdf-compress.wasm/tree/commercial), used by [saferpdf.com](https://www.saferpdf.com/) (a service that I created based on this code) and it works with WebAssembly and it is fully async and therefore will not block the main thread.

You can tinker around and if you need more help, just contact me (all my contact info are on my blog)

**Comment by laurentmmeyer** [comment]
Actually look at other branches as well, I'm not sure that this is only on commercial. I think that [webworker](https://github.com/laurentmmeyer/ghostscript-pdf-compress.wasm/tree/web-worker) is even more what you need.

I'm going to clean up branches in the weekend and add/update some features from the community

**Comment by TIT8** [comment]
Thank you, really. 
In the weekend I will try.
